[package]
name = "radtype"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "radtype"

[dependencies]
ferris-says = "0.2"
piston = "0.53.0"
piston2d-graphics = "0.43.0"
pistoncore-glutin_window = "0.71.0"
piston2d-opengl_graphics = "0.82.0"

